Repository Financial-Times/engineering-progression, pull requests merged in 2019-09, with the labels that each got.

#263 J->M - more positive description of no distraction competency
  data/competencies.yml
Labels: area: delivery, level: J→M

#265 Add examples for "debugs independently" competency
  data/competencies.yml
Labels: area: technical, level: J→M

#266 Add examples for "writes clear tickets" competency
  data/competencies.yml
Labels: area: communication, level: J→M

#267 Add examples to "presents their work" competency
  data/competencies.yml
Labels: area: communication, level: J→M

#268 Add examples to "collaborates with team" competency
  data/competencies.yml
Labels: area: delivery, level: J→M

#264 Add examples for "learns and improves" competency
  data/competencies.yml
Labels: area: technical, level: J→M
